### ISSUE TITLE
Problems in docs for preconditioner

### ISSUE THREAD

**Issue by ibell** [TSTK/ACHP#15]
@bo3mrh I believe you have introduced some issues in the fixes to the documentation for the Preconditioner.  You use humid air properties on a humid-air basis in some places (\rho_{ha} for instance), while the units at the bottom are still on a dry-air basis.  Please fix and file a pull request.

**Comment by bo3mrh** [comment]
@ibell Sorry for any confusion. I check out the code (https://github.com/TSTK/ACHP/blob/master/ACHP/Preconditioners.py#L17). It is a typo in the documentation. It should be \rho_{da}. However, the unit at the bottom is right. I will fix this in the next pull. 
Thank you for pointing this out, tho
