### ISSUE TITLE
ValueError: HAProps failed ungracefully with inputs: "W","T",2.7852603934336025e+02,"P",1.0132500000000000e+05,"H",1.4114309647910737e+04 

### ISSUE THREAD

**Issue by ranhamku** [TSTK/ACHP#30]
Hi, 

I try to run CycleTest with Heat Pump Model, but I just got the following Error:

ValueError: HAProps failed ungracefully with inputs: "W","T",2.7852603934336025e+02,"P",1.0132500000000000e+05,"H",1.4114309647910737e+04 

My python version is 3.6.1 | Anaconda 4.4.0 (64-bit)
I'm confused, is there something wrong with my python version?

Best Wishes

**Comment by abahman** [comment]
which version of CoolProp you are using ?

**Comment by abahman** [comment]
by the way, we recommed to install the latest CoolProp 6.1.0 which works only on python 2.7.x and 3.5.x

**Comment by ibell** [comment]
New CoolProp should also work on python 3.6, in fact I use python 3.6 for
pretty much all my python work.

**Comment by abahman** [comment]
@ibell this is odd. Pip only shows that 6.0.0 is the latest available version when I work with python 3.6.x ?

```
(python3) Ammars-MacBook-Pro:~ ammarbahman$ pip install coolprop==6.1.0
Collecting coolprop==6.1.0
  Could not find a version that satisfies the requirement coolprop==6.1.0 (from versions: 2.0.1, 2.0.2, 2.0.4, 2.0.5, 2.0.6, 2.1, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.3, 2.4, 2.5, 3.0.1, 3.1, 3.1.1, 3.1.2, 3.2.0, 3.3.0, 4.0.0b0, 4.0.0, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.2.2, 4.2.3, 4.2.4, 4.2.5, 5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.0.4, 5.0.5, 5.0.6, 5.0.7, 5.0.8, 5.1.0, 5.1.1, 5.1.2, 6.0.0)
No matching distribution found for coolprop==6.1.0
```

**Comment by ibell** [comment]
You need to install development binaries,which are pretty stable given the
pace of development of CoolProp:
http://www.coolprop.org/coolprop/wrappers/Python/index.html#automatic-installation
(the second option)

**Comment by abahman** [comment]
Thank you.
The reason I mention it in the first place because I did not find it for python 3.6.x here: https://pypi.python.org/pypi/CoolProp/

**Comment by ibell** [comment]
Yes, that will be remedied when we release 6.2, which has no clear timeline
currently.

**Comment by ranhamku** [comment]
@abahman 
I use the CoolProp version 6.1.1 for python 3.6.1 | Anaconda 4.4.0 (64-bit)

**Comment by ranhamku** [comment]
@ibell 
I also use CoolProp 6.1.1, and my python version is 3.6.1 | Anaconda 4.4.0, but when I ran the cycleTest.py, just met the problem mentioned above, I google it, and said could be the reason of the version of CoopProp, I reinstalled my CoopProp, still didn't work.

**Comment by abahman** [comment]
@ranhamku I got the same error as yours with CP 6.1.1. I suggest to use the latest stable version which is CP 6.1.0. 
You might also send an issue to https://github.com/CoolProp/CoolProp/issues

**Comment by ranhamku** [comment]
@abahman where did you find CP 6.1.0? I can just install 6.0.0 with pip and 6.1.1.
I've send the issue to the website you mentioned. But got no answer.

**Comment by abahman** [comment]
@ranhamku There you go: https://sourceforge.net/projects/coolprop/files/CoolProp/6.1.0/

**Comment by ranhamku** [comment]
@abahman thank, I should also install python 3.4

**Comment by abahman** [comment]
@ranhamku I think you will be fine with python 3.5

**Comment by ranhamku** [comment]
ok,let me have a try.

**Comment by ranhamku** [comment]
@abahman  sorry for the interruption, but could you please tell me the range of three inputs of T,P,H? Cause I want to run the cycleTest on my machine learning algorithm, and I want to know the range of the input value. Could you please tell me about that? And another question, if i modify the three inputs in the cycleTest within the range, can I get an optimal COP? Thanks a lot

**Comment by abahman** [comment]
@ranhamku I am not sure if I got your question right. With th cycle model there are many inputs to adjust (not sure what do mean by the three inputs T,P,H)?

**Comment by ranhamku** [comment]
@abahman I mean in the HPTest.py, there are many parameters in line set parameters like this: params={
        'L':7.6,
        'k_tube':0.19,
        't_insul':0.02,
        'k_insul':0.036,
        'T_air':297,
        'Ref': Cycle.Ref,
        'Backend': Cycle.Backend,
        'h_air':6,
        }
 can I just change the params in order to get an optimal COP without changing another parameters in HPTest.py?

**Comment by abahman** [comment]
@ranhamku I can not give you a straight answer becasue it depends on your objective function and your constrains. Ultimetly, changing the parameters (physical geometry) of the cycle's component will change the perofrmance.

**Comment by ranhamku** [comment]
@abahman I mean I just change the line set  parameters without changing another constrains, and then want to see if I can get a better performance

**Comment by ranhamku** [comment]
@abahman and if I could do that, could you please tell me the range of these parameters of line set? Thanks a lot.

**Comment by abahman** [comment]
@ranhamku Sure you can change only the line set parameters. As for the limits, there is no ceratin answer for this. For example, the unit is designed for a specific location, and as a designer, you limit the length of the return/supply line based on the site or unit location.

**Comment by ranhamku** [comment]
or if I set the length as constant and change another parameters? like
t_insul and T_air? can I get a better COP?

Ammar Bahman <notifications@github.com>于2017年11月29日 周三20:02写道：
